### ISSUE TITLE
changed objects not provided in /read request

### ISSUE THREAD

**Issue by juliand665** [mangelio/app#128]
This bug comes up in several situations. One example follows:

1. add a new map to a site
2. update the data in the iOS app (`/read` request)
3. add a new version to the map
4. update the data in the iOS app again

expected: the newly updated map is provided, since the meta object sent in the request has an older `lastChangeTime`
actual: despite the `lastChangeTime` in the request being correct (older) and the `lastChangeTime` in the response to a clean read request being correct (newer), the object in question is not provided in response to the read request mentioning the current version, e.g. `{"id":"A5E90271-07B4-4FC4-B676-6EEFA7BD106E","lastChangeTime":"2019-03-04T04:22:42Z"}` while the clean request yields
`{"id":"A5E90271-07B4-4FC4-B676-6EEFA7BD106E","lastChangeTime":"2019-03-04T05:31:08+01:00"}`

This also occurs e.g. when registering new issues or changing their description. I haven't tested more than that, but I bet it happens for everything.

**Comment by famoser** [comment]
The issue occurs with timestamps which differ in less than one day. The problem is that doctrine (the DAL) does not serialize datetime ISO compliant as expected, but rather as Y-m-d H:s. This is an issue as the `/read` request skips the DAL and directly executes against the db a (string) comparison, but of an ISO serialized datetime. But `2019-03-04T04:22:42 > 2019-03-04 05:31:08`; hence the issue.

**Comment by famoser** [comment]
The integration test checking this feature did not detect the error as it used a date which was a day old to check whether it would detect that (which it did)
